#ifndef FLOGGING_H
#define FLOGGING_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(fLib)
Q_DECLARE_LOGGING_CATEGORY(fLibDB)
Q_DECLARE_LOGGING_CATEGORY(fLibDBUpdater)
Q_DECLARE_LOGGING_CATEGORY(fLibCrawler)
Q_DECLARE_LOGGING_CATEGORY(fLibGame)
Q_DECLARE_LOGGING_CATEGORY(fLibArt)
Q_DECLARE_LOGGING_CATEGORY(fLibUpdater)
Q_DECLARE_LOGGING_CATEGORY(fLibDownload)
Q_DECLARE_LOGGING_CATEGORY(fLibWatchedFolder)

#endif // FLOGGING_H
